# Generated by Django 4.1.6 on 2023-02-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(upload_to='images', verbose_name='Фото 1')),
                ('title_one', models.CharField(max_length=200, verbose_name='Текст внутри фото 1')),
                ('image_two', models.ImageField(upload_to='images', verbose_name='Фото 2')),
                ('title_two', models.CharField(max_length=200, verbose_name='Текст внутри фото 2')),
                ('image_three', models.ImageField(upload_to='images', verbose_name='Фото 3')),
                ('title_three', models.CharField(max_length=200, verbose_name='Текст внутри фото 3')),
                ('image_four', models.ImageField(upload_to='images', verbose_name='Фото 4')),
                ('title_four', models.CharField(max_length=200, verbose_name='Текст внутри фото 4')),
                ('image_five', models.ImageField(upload_to='images', verbose_name='Фото 5')),
                ('title_five', models.CharField(max_length=200, verbose_name='Текст внутри фото 5')),
                ('image_six', models.ImageField(upload_to='images', verbose_name='Фото 6')),
                ('title_six', models.CharField(max_length=200, verbose_name='Текст внутри фото 6')),
                ('image_metod', models.ImageField(upload_to='images', verbose_name='Методичка')),
                ('title_metod', models.TextField()),
                ('image_info', models.ImageField(upload_to='images', verbose_name='Фото рядом с тестом')),
                ('title_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.URLField(max_length=1000, verbose_name='Ссылка на видео')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='WhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.URLField(max_length=1000, verbose_name='Ссылка WA')),
            ],
            options={
                'verbose_name': 'Ссылка WA',
                'verbose_name_plural': 'Ссылка WA',
            },
        ),
    ]
